/**
 * Canonical columns exposed by data_pipeline.shiprocket_order_explorer (migration 027+).
 * Filter metadata, list queries, overview, and export must only reference this set.
 */
export const SHIPROCKET_EXPLORER_COLUMNS = [
  "sr_order_id",
  "unique_key",
  "shipment_status_id",
  "shipment_status",
  "scans1_status",
  "scans1_sr_status_label",
  "scans1_sr_status",
  "scans1_location",
  "scans1_date",
  "scans1_activity",
  "scans0_status",
  "scans0_sr_status_label",
  "scans0_sr_status",
  "scans0_location",
  "scans0_date",
  "scans0_activity",
  "order_id",
  "is_return",
  "etd",
  "current_ts",
  "current_status_id",
  "current_status",
  "courier_name",
  "channel_id",
  "awb",
  "order_date",
  "created_at_sr",
  "shiprocket_customer_name",
  "customer_email",
  "shiprocket_customer_phone",
  "pickup_location",
  "payment_status",
  "payment_method",
  "order_total",
  "tax",
  "order_status",
  "order_status_code",
  "shipment_id",
  "tracking_url",
  "delivered_date",
  "products",
  "last_local_api_sync_at",
  "last_webhook_sync_at",
  "return_awb_code",
  "awb_assigned_date",
  "pickup_scheduled_date",
  "pickup_exception_reason",
  "undelivered_reason",
  "undelivered_reason_code",
  "pick_exception_reason_code",
  "delivery_attempt_count",
  "pickup_attempt_count",
  "qc_image",
  "qc_failure_reason",
  "pod_status",
  "pod",
  "shipping_method",
  "created_at",
  "updated_at",
  "order_id_shopify_format",
  "shopify_order_identifier",
  "customer_name_shopify",
  "customer_phone_shopify",
  "coach",
  "last_enriched_at",
  "billing_name",
  "billing_email",
  "billing_phone",
  "source_date",
  "status_bucket",
  "payment_bucket",
  "order_total_num",
  "has_scan_activity",
  "api_enriched",
  "shopify_matched",
  "has_raw_payload",
  "remittance_count",
  "latest_crf_id",
  "latest_utr",
  "latest_remittance_date",
  "latest_remittance_status",
  "latest_remittance_type",
  "latest_remittance_method",
  "latest_order_settlement_value",
  "latest_total_adjusted_amt",
  "latest_channel_name",
  "latest_linked_crf_ids",
  "latest_cod_available",
  "latest_standard_cod_available",
  "latest_instant_cod_available",
  "latest_early_cod_available",
  "latest_freight_charges_from_cod",
  "latest_rto_reversal_amount",
  "latest_early_cod_charges",
  "latest_instant_cod_charges",
  "latest_remittance_amount",
  "latest_adjusted_amount",
  "latest_remarks",
  "remittance_match_status",
  "pabbly_status",
  "pabbly_attempt_count",
  "pabbly_first_attempt_at",
  "pabbly_last_attempt_at",
  "pabbly_sent_at",
  "pabbly_last_error",
  "pabbly_next_attempt_at",
  "pabbly_final_failure_at",
  "pabbly_delivery_count",
  "pabbly_sent_count",
  "pabbly_failed_count",
] as const;

export type ShiprocketExplorerColumn = (typeof SHIPROCKET_EXPLORER_COLUMNS)[number];

export const SHIPROCKET_EXPLORER_COLUMN_SET = new Set<string>(SHIPROCKET_EXPLORER_COLUMNS);

export function assertExplorerQueryableColumns(columns: string[]): void {
  const missing = columns.filter((col) => !SHIPROCKET_EXPLORER_COLUMN_SET.has(col));
  if (missing.length > 0) {
    throw new Error(`Explorer query references missing columns: ${missing.join(", ")}`);
  }
}
