-- 024_shiprocket_legacy_analytics.sql
-- Legacy Sheet-label projection + data-quality view.
-- Does not replace existing analytics.shiprocket_* views.

create or replace view analytics.shiprocket_legacy_order_rows as
select
  coalesce(o.unique_key, 'shiprocket_order:' || o.sr_order_id) as "Shiprocket Unique Key",
  o.sr_order_id as "Sr Order Id",
  o.shipment_status_id as "Shipment Status Id",
  o.shipment_status as "Shipment Status",
  o.scans1_status as "Scans 1 Status",
  o.scans1_sr_status_label as "Scans 1 Sr-status-label",
  o.scans1_sr_status as "Scans 1 Sr-status",
  o.scans1_location as "Scans 1 Location",
  o.scans1_date as "Scans 1 Date",
  o.scans1_activity as "Scans 1 Activity",
  o.scans0_status as "Scans 0 Status",
  o.scans0_sr_status_label as "Scans 0 Sr-status-label",
  o.scans0_sr_status as "Scans 0 Sr-status",
  o.scans0_location as "Scans 0 Location",
  o.scans0_date as "Scans 0 Date",
  o.scans0_activity as "Scans 0 Activity",
  o.order_id as "Order Id",
  o.is_return as "Is Return",
  o.etd as "Etd",
  o.current_ts as "Current Timestamp",
  o.current_status_id as "Current Status Id",
  o.current_status as "Current Status",
  o.courier_name as "Courier Name",
  o.channel_id as "Channel Id",
  o.awb as "Awb",
  o.order_date as "Order Date",
  o.created_at_sr as "Created At",
  e.customer_name_shopify as "Customer Name",
  o.customer_email as "Customer Email",
  e.customer_phone_shopify as "Customer Phone",
  o.pickup_location as "Pickup Location",
  o.payment_status as "Payment Status",
  o.payment_method as "Payment Method",
  o.order_total as "Order Total",
  o.tax as "Tax",
  o.order_status as "Order Status",
  o.order_status_code as "Order Status Code",
  o.shipment_id as "Shipment ID",
  o.tracking_url as "Tracking URL",
  o.delivered_date as "Delivered Date",
  o.products as "Products",
  o.last_local_api_sync_at as "Last Local API Sync At",
  o.last_webhook_sync_at as "Last Webhook Sync At",
  o.raw_payload as "Raw Shiprocket JSON",
  e.coach as "Coach",
  e.order_id_shopify_format as "order id shopify format",
  ''::text as "Column 47",
  ''::text as "Column 48",
  ''::text as "Column 49",
  ''::text as "Column 50",
  ''::text as "Column 51",
  ''::text as "Column 52",
  ''::text as "Column 53",
  ''::text as "Column 54",
  ''::text as "Column 55",
  ''::text as "Column 56",
  ''::text as "Column 57",
  ''::text as "Column 58",
  ''::text as "Column 59",
  ''::text as "Column 60",
  ''::text as "Column 61",
  ''::text as "Column 62",
  ''::text as "Column 63",
  ''::text as "Column 64",
  ''::text as "Column 65",
  ''::text as "Column 66",
  ''::text as "Column 67"
from data_pipeline.shiprocket_orders o
left join data_pipeline.shiprocket_order_enrichment e
  on e.sr_order_id = o.sr_order_id;

create or replace view analytics.shiprocket_data_quality as
select
  count(*) as orders_total,
  count(*) filter (where o.order_id is null or btrim(o.order_id) = '') as missing_order_id,
  count(*) filter (where o.awb is null or btrim(o.awb) = '') as missing_awb,
  count(*) filter (where e.order_id_shopify_format is null or e.order_id_shopify_format = '') as missing_shopify_8_digit,
  count(*) filter (where e.shopify_order_identifier is not null) as shopify_matched,
  count(*) filter (where e.sr_order_id is not null and e.shopify_order_identifier is null) as shopify_unmatched,
  count(*) filter (where e.customer_name_shopify is null or e.customer_name_shopify = '') as missing_customer_name,
  count(*) filter (where e.customer_phone_shopify is null or e.customer_phone_shopify = '') as missing_customer_phone,
  count(*) filter (where o.last_local_api_sync_at is null) as last_api_sync_missing,
  max(o.last_webhook_sync_at) as last_webhook_sync
from data_pipeline.shiprocket_orders o
left join data_pipeline.shiprocket_order_enrichment e
  on e.sr_order_id = o.sr_order_id;

-- Explorer projection (snake_case, no raw JSON) for dashboard list/filter.
create or replace view data_pipeline.shiprocket_order_explorer as
select
  o.sr_order_id,
  o.unique_key,
  o.shipment_status_id,
  o.shipment_status,
  o.scans1_status,
  o.scans1_sr_status_label,
  o.scans1_sr_status,
  o.scans1_location,
  o.scans1_date,
  o.scans1_activity,
  o.scans0_status,
  o.scans0_sr_status_label,
  o.scans0_sr_status,
  o.scans0_location,
  o.scans0_date,
  o.scans0_activity,
  o.order_id,
  o.is_return,
  o.etd,
  o.current_ts,
  o.current_status_id,
  o.current_status,
  o.courier_name,
  o.channel_id,
  o.awb,
  o.order_date,
  o.created_at_sr,
  o.customer_name as shiprocket_customer_name,
  o.customer_email,
  o.customer_phone as shiprocket_customer_phone,
  o.pickup_location,
  o.payment_status,
  o.payment_method,
  o.order_total,
  o.tax,
  o.order_status,
  o.order_status_code,
  o.shipment_id,
  o.tracking_url,
  o.delivered_date,
  o.products,
  o.last_local_api_sync_at,
  o.last_webhook_sync_at,
  o.return_awb_code,
  o.awb_assigned_date,
  o.pickup_scheduled_date,
  o.pickup_exception_reason,
  o.undelivered_reason,
  o.undelivered_reason_code,
  o.pick_exception_reason_code,
  o.delivery_attempt_count,
  o.pickup_attempt_count,
  o.qc_image,
  o.qc_failure_reason,
  o.pod_status,
  o.pod,
  o.shipping_method,
  o.created_at,
  o.updated_at,
  e.order_id_shopify_format,
  e.shopify_order_identifier,
  e.customer_name_shopify,
  e.customer_phone_shopify,
  e.coach,
  e.last_enriched_at
from data_pipeline.shiprocket_orders o
left join data_pipeline.shiprocket_order_enrichment e
  on e.sr_order_id = o.sr_order_id;

grant select on analytics.shiprocket_legacy_order_rows to service_role, authenticated;
grant select on analytics.shiprocket_data_quality to service_role, authenticated;
grant select on data_pipeline.shiprocket_order_explorer to service_role;
